"""L0 first-slice baseline schema

Revision ID: 0001_l0_first_slice
Revises:
Create Date: 2026-09-02

Baseline decision: this migration creates the eleven first-slice tables with
explicit DDL, frozen as they stood when S1 was merged (464829a). It also
enables the pgvector extension so later legal-passage migrations do not have to
recreate the database. Later schema changes must be explicit migrations
(preferably autogenerate + manual review), not edits to this baseline.

History: the original version called ``Base.metadata.create_all``. That read
the *current* ORM, so on an empty database it also created ``sources``,
``legal_units`` and ``system_settings``, and migration 0002 then failed with
DuplicateTable (``make migrate`` and ``make reset`` both broke on a fresh DB).
The DDL below was generated by autogenerate for exactly those eleven tables
and is identical to what the old create_all produced at S1, so databases that
already ran 0001 are unaffected. tests/persistence/test_live_migrations.py
guards the upgrade/downgrade round trip on a fresh database.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_l0_first_slice"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('evaluation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_state', sa.String(length=48), nullable=False),
    sa.Column('expected_blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scenario_tag', sa.String(length=64), nullable=True),
    sa.Column('applicable_date', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("expected_state IN ('human_review_required', 'research_only_output', 'stop_and_escalate')", name='ck_evaluation_case_state'),
    sa.CheckConstraint('synthetic = TRUE', name='ck_evaluation_case_synthetic'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_evaluation_case_logical_id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('package', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('professional_validation_status', sa.String(length=32), server_default='unverified', nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), server_default='candidate', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction', 'package', 'version', name='uq_rule_set_version')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('package', sa.String(length=32), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('case_status', sa.String(length=48), server_default='draft', nullable=False),
    sa.Column('release_level', sa.String(length=4), server_default='L0', nullable=False),
    sa.Column('applicable_date', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("case_status IN ('analyzing', 'approved', 'archived', 'draft', 'interviewing', 'invalidated', 'needs_human_judgment', 'pending_review', 'waiting_client_evidence', 'waiting_fact_confirmation')", name='ck_case_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_organization_id'), 'cases', ['organization_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('rule_set_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_case_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_state', sa.String(length=48), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("terminal_state IN ('human_review_required', 'research_only_output', 'stop_and_escalate')", name='ck_eval_run_state'),
    sa.ForeignKeyConstraint(['evaluation_case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_evaluation_case_id'), 'evaluation_runs', ['evaluation_case_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_organization_id'), 'evaluation_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_rule_set_id'), 'evaluation_runs', ['rule_set_id'], unique=False)
    op.create_table('rule_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_set_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('node', sa.String(length=48), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('required_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('depends_on_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.String(length=16), nullable=True),
    sa.Column('effective_to', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='unverified', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node IN ('anti_hybrid', 'compliance_filing', 'economic_substance', 'financial_entity_exclusion', 'foreign_tax_switchover', 'human_gate', 'income_characterisation', 'main_purpose', 'participation_basic', 'receipt', 'scope')", name='ck_rule_node_node'),
    sa.CheckConstraint("status IN ('rejected', 'unverified', 'verified')", name='ck_rule_node_status'),
    sa.CheckConstraint('ordinal BETWEEN 0 AND 10', name='ck_rule_node_ordinal'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_set_id', 'rule_id', name='uq_rule_node_in_set')
    )
    op.create_index(op.f('ix_rule_nodes_rule_set_id'), 'rule_nodes', ['rule_set_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('node', sa.String(length=48), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('output', sa.String(length=48), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node IN ('anti_hybrid', 'compliance_filing', 'economic_substance', 'financial_entity_exclusion', 'foreign_tax_switchover', 'human_gate', 'income_characterisation', 'main_purpose', 'participation_basic', 'receipt', 'scope')", name='ck_eval_result_node'),
    sa.CheckConstraint("output IN ('condition_not_demonstrated', 'conflict', 'human_review_required', 'not_satisfied', 'satisfied', 'unknown')", name='ck_eval_result_output'),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_evaluation_run_id'), 'evaluation_results', ['evaluation_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_organization_id'), 'evaluation_results', ['organization_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('income_event_id', sa.String(length=64), nullable=True),
    sa.Column('field_name', sa.String(length=96), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('confirmation_status', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_quote', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), server_default='system', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confirmation_status IN ('advisor_confirmed', 'ai_candidate', 'assumed', 'client_statement', 'conflict', 'externally_evidenced', 'unknown')", name='ck_fact_confirmation'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'field_name', name='uq_fact_case_field')
    )
    op.create_index(op.f('ix_facts_case_id'), 'facts', ['case_id'], unique=False)
    op.create_index(op.f('ix_facts_organization_id'), 'facts', ['organization_id'], unique=False)
    op.create_table('rule_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('rule_set_id', sa.Integer(), nullable=False),
    sa.Column('rule_node_id', sa.Integer(), nullable=True),
    sa.Column('execution_batch', sa.String(length=64), nullable=False),
    sa.Column('node', sa.String(length=48), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('output', sa.String(length=48), nullable=False),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node IN ('anti_hybrid', 'compliance_filing', 'economic_substance', 'financial_entity_exclusion', 'foreign_tax_switchover', 'human_gate', 'income_characterisation', 'main_purpose', 'participation_basic', 'receipt', 'scope')", name='ck_rule_exec_node'),
    sa.CheckConstraint("output IN ('condition_not_demonstrated', 'conflict', 'human_review_required', 'not_satisfied', 'satisfied', 'unknown')", name='ck_rule_exec_output'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_node_id'], ['rule_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_executions_case_id'), 'rule_executions', ['case_id'], unique=False)
    op.create_index(op.f('ix_rule_executions_execution_batch'), 'rule_executions', ['execution_batch'], unique=False)
    op.create_index(op.f('ix_rule_executions_organization_id'), 'rule_executions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rule_executions_rule_set_id'), 'rule_executions', ['rule_set_id'], unique=False)
    op.create_table('fact_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmation_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_quote', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confirmation_status IN ('advisor_confirmed', 'ai_candidate', 'assumed', 'client_statement', 'conflict', 'externally_evidenced', 'unknown')", name='ck_fact_version_confirmation'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_id', 'version_no', name='uq_fact_version')
    )
    op.create_index(op.f('ix_fact_versions_fact_id'), 'fact_versions', ['fact_id'], unique=False)
    op.create_index(op.f('ix_fact_versions_organization_id'), 'fact_versions', ['organization_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_fact_versions_organization_id'), table_name='fact_versions')
    op.drop_index(op.f('ix_fact_versions_fact_id'), table_name='fact_versions')
    op.drop_table('fact_versions')
    op.drop_index(op.f('ix_rule_executions_rule_set_id'), table_name='rule_executions')
    op.drop_index(op.f('ix_rule_executions_organization_id'), table_name='rule_executions')
    op.drop_index(op.f('ix_rule_executions_execution_batch'), table_name='rule_executions')
    op.drop_index(op.f('ix_rule_executions_case_id'), table_name='rule_executions')
    op.drop_table('rule_executions')
    op.drop_index(op.f('ix_facts_organization_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_case_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_evaluation_results_organization_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_evaluation_run_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_rule_nodes_rule_set_id'), table_name='rule_nodes')
    op.drop_table('rule_nodes')
    op.drop_index(op.f('ix_evaluation_runs_rule_set_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_organization_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_evaluation_case_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_cases_organization_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('rule_sets')
    op.drop_table('organizations')
    op.drop_table('evaluation_cases')
    op.execute("DROP EXTENSION IF EXISTS vector")
